name: hspec-webdriver
version: '1.1.0'
synopsis: Write end2end web application tests using webdriver and hspec
description: ! 'For end to end testing of web applications from Haskell, the
  <https://hackage.haskell.org/package/webdriver webdriver> package is a great tool
  but just contains the code to communicate with the browser.  This package integrates webdriver
  with <http://hspec.github.io hspec>.'
category: Web
author: John Lenz <lenz@math.uic.edu>
maintainer: John Lenz <lenz@math.uic.edu>
license: MIT
homepage: https://bitbucket.org/wuzzeb/webdriver-utils
git: https://bitbucket.org/wuzzeb/webdriver-utils
extra-source-files:
- README.md
- Changelog.md
ghc-options:
- -Wall
- -O2
dependencies:
- base >=4.9
- HUnit
- aeson
- data-default >=0.5
- hashable >=1.2
- hspec-core >= 2.5.0
- hspec
- interpolate
- lifted-base >=0.2
- stm >=2.4
- text >=0.11
- transformers >=0.3
- unordered-containers >=0.2
- webdriver >=0.6.1 && <0.9
library:
  source-dirs: ./.
  exposed-modules:
  - Test.Hspec.WebDriver
stability: Experimental
